name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup jdk 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
    - name: compile classes
      run: find . -name '*.java' | xargs javac
    - name: build jar archive
      run: find . -name '*.class' | xargs jar cvmf META-INF/MANIFEST.MF TimeInput.jar
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: TimeInput.jar
